export const products = [ 
    {
        productName: "Toallón Hydra 80x60 Secado rápido",
        price: 800,
        Id: 1,
        category: "accesorios",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 10,
    },
    {
        productName: "Antiparras Arena Ultra Mirror",
        price: 8500,
        Id: 2,
        category: "ArticulosDeportivos",
        description: "Antiparras profesionales ARENA ULTRA MIRROR",
        img: "https://res.cloudinary.com/dkolnsx2y/image/upload/e_background_removal/v1670544172/arena-cobra-ultra-swipe-mirror-swimming-goggles_ot8eaz.jpg",
        stock: 3,
    },
    {
        productName: "Antiparras Arena The One",
        price: 4900,
        Id: 3,
        category: "ArticulosDeportivos",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 5,
    },
    {
        productName: "Antiparras Arena Zoom XFIT",
        price: 2800,
        Id: 4,
        category: "ArticulosDeportivos",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 10,
    },
    {
        productName: "Aletas cortas Arena 35-46",
        price: 5000,
        Id: 5,
        category: "ArticulosDeportivos",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "https://res.cloudinary.com/dkolnsx2y/image/upload/v1670544609/kisspng-zoggs-diving-swimming-fins-goggles-swimsuit-color-flippers-5ae1311882e743.2171193415247076085362_xlvo70.jpg" ,
        stock: 20,
    },
    {
        productName: "Snorkel frontal",
        price: 4000,
        Id: 6,
        category: "ArticulosDeportivos",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.https://res.cloudinary.com/dkolnsx2y/image/upload/v1670544768/finis-stability-frontal-snorkel_uhyxho.jpgcom" ,
        stock: 5,
    },
    {
        productName: "PullBouy Goma espuma",
        price: 3000,
        Id: 7,
        category: "ArticulosDeportivos",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.cohttps://res.cloudinary.com/dkolnsx2y/image/upload/v1670544981/Hb8ecc9f4738f4af5be7172ccb20eba51H_sl9pck.jpgm" ,
        stock: 10,
    },
    {
        productName: "PullBouy PVC",
        price: 1500,
        Id: 8,
        category: "ArticulosDeportivos",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.cohttps://res.cloudinary.com/dkolnsx2y/image/upload/v1670544981/b4c33786-057d-4a92-974f-1d951ec99260_1.dd1ae9fd159bebb929f10994fbbd2c00_gbkd05.jpgm" ,
        stock: 5,
    },
    {
        productName: "Gorra de silicona",
        price: 1000,
        Id: 9,
        category: "ArticulosDeportivos",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.https://res.cloudinary.com/dkolnsx2y/image/upload/v1670544919/s-l1600_fiqkzk.jpg" ,
        stock: 20,
    },
    {
        productName: "Gorra de Lycra",
        price: 600,
        Id: 10,
        category: "ArticulosDeportivos",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.https://res.cloudinary.com/dkolnsx2y/image/upload/v1670544809/51JuvqH161L._AC_SX425__dbtciv.jpg" ,
        stock: 40,
    },
    {
        productName: "Mochila Arena Ultra",
        price: 15000,
        Id: 11,
        category: "accesorios",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "https://res.cloudinary.com/dkolnsx2y/image/upload/v1670544826/Bolsa-de-nataci-n-de-gran-capacidad-resistente-al-agua-bolso-para-nataci-n-profesional-ASS5734.jpg_Q90.jpg__awygjx.jpg" ,
        stock: 100,
    },
    {
        productName: "Mochila de red",
        price: 600,
        Id: 12,
        category: "accesorios",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 20,
    },
    {
        productName: "Bolso Arena Hydra",
        price: 20000,
        Id: 13,
        category: "accesorios",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "https://res.cloudinary.com/dkolnsx2y/image/upload/v1670544825/f5cdd85401aec0f65ef68bcc96ff651e--backpack-colors_jwa8oi.jpg" ,
        stock: 20,
    },
    {
        productName: "Chomba Hydra",
        price: 4500,
        Id: 14,
        category: "indumentaria",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 20,
    },
    {
        productName: "Conjunto de buzo Hydra",
        price: 8500,
        Id: 15,
        category: "indumentaria",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 20,
    },
    {
        productName: "Short Hydra",
        price: 2500,
        Id: 16,
        category: "indumentaria",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 20,
    },
    {
        productName: "Campera Hydra",
        price: 5000,
        Id: 17,
        category: "accesorios",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 20,
    },
    {
        productName: "Toalla Hydra 30x20 Con logo",
        price: 800,        
        Id: 18,
        category: "accesorios",
        description: "Toalla de secado rápido de 30x20cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 10,
    }
]