export const products = [ 
    {
        productName: "Toallón Hydra 80x60 Secado rápido",
        price: 800,
        Id: 1,
        category: "accesorios",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 10,
    },
    {
        productName: "Antiparras Arena Ultra Mirror",
        price: 8500,
        Id: 2,
        category: "ArticulosDeportivos",
        description: "Antiparras profesionales ARENA ULTRA MIRROR",
        img: "http://.com" ,
        stock: 3,
    },
    {
        productName: "Antiparras Arena The One",
        price: 4900,
        Id: 3,
        category: "ArticulosDeportivos",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 5,
    },
    {
        productName: "Antiparras Arena Zoom XFIT",
        price: 2800,
        Id: 4,
        category: "ArticulosDeportivos",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 10,
    },
    {
        productName: "Aletas cortas Arena 35-46",
        price: 5000,
        Id: 5,
        category: "ArticulosDeportivos",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 20,
    },
    {
        productName: "Snorkel frontal",
        price: 4000,
        Id: 6,
        category: "ArticulosDeportivos",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 5,
    },
    {
        productName: "PullBouy Goma espuma",
        price: 3000,
        Id: 7,
        category: "ArticulosDeportivos",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 10,
    },
    {
        productName: "PullBouy PVC",
        price: 1500,
        Id: 8,
        category: "ArticulosDeportivos",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 5,
    },
    {
        productName: "Gorra de silicona",
        price: 1000,
        Id: 9,
        category: "ArticulosDeportivos",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 20,
    },
    {
        productName: "Gorra de Lycra",
        price: 600,
        Id: 10,
        category: "ArticulosDeportivos",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 40,
    },
    {
        productName: "Mochila Arena Ultra",
        price: 15000,
        Id: 11,
        category: "accesorios",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 100,
    },
    {
        productName: "Mochila de red",
        price: 600,
        Id: 12,
        category: "accesorios",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 20,
    },
    {
        productName: "Bolso Arena Hydra",
        price: 20000,
        Id: 13,
        category: "accesorios",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 20,
    },
    {
        productName: "Chomba Hydra",
        price: 4500,
        Id: 14,
        category: "indumentaria",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 20,
    },
    {
        productName: "Conjunto de buzo Hydra",
        price: 8500,
        Id: 15,
        category: "indumentaria",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 20,
    },
    {
        productName: "Short Hydra",
        price: 2500,
        Id: 16,
        category: "indumentaria",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 20,
    },
    {
        productName: "Campera Hydra",
        price: 5000,
        Id: 17,
        category: "accesorios",
        description: "Toalla de secado rápido de 80x60cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 20,
    },
    {
        productName: "Toalla Hydra 30x20 Con logo",
        price: 800,        
        Id: 18,
        category: "accesorios",
        description: "Toalla de secado rápido de 30x20cm con logo de hidra bordado",
        img: "http://.com" ,
        stock: 10,
    }
]